import os

# 1. Add email report endpoint to backend
main_path = '/Users/sakthivel-1528/Personal/sem-app/backend/main_with_ads.py'
with open(main_path) as f:
    content = f.read()

email_endpoint = '''
@app.post("/api/send-report")
async def send_seo_report(request: Request):
    """Send SEO report via email using Resend."""
    try:
        body = await request.json()
        url = body.get("url", "")
        email = body.get("email", "")
        seo_report = body.get("seo_report", {})
        
        if not email:
            raise HTTPException(status_code=400, detail="Email required")
        
        resend_api_key = os.environ.get("RESEND_API_KEY", "")
        if not resend_api_key:
            raise HTTPException(status_code=500, detail="Email service not configured")
        
        # Build HTML report
        score = seo_report.get("overall_seo_score", 0)
        score_color = "#22c55e" if score >= 70 else "#f59e0b" if score >= 40 else "#ef4444"
        summary = seo_report.get("ai_summary", "")
        strengths = seo_report.get("strengths", [])
        weaknesses = seo_report.get("weaknesses", [])
        keywords = seo_report.get("keyword_suggestions", [])
        sem = seo_report.get("sem_recommendations", {})
        budget = sem.get("monthly_budget_inr", 0)
        clicks = sem.get("monthly_clicks_estimate", "N/A")
        cpc = sem.get("estimated_cpc_inr", 0)
        
        strengths_html = "".join([f'<li style="color:#22c55e;margin-bottom:6px">✓ {s.get("point","")}</li>' for s in strengths[:5]])
        weaknesses_html = "".join([f'<li style="color:#ef4444;margin-bottom:6px">✗ {w.get("point","")} — {w.get("fix","")}</li>' for w in weaknesses[:5]])
        keywords_html = "".join([f'<span style="background:#f0f9ff;color:#0369a1;padding:3px 8px;border-radius:10px;margin:3px;display:inline-block;font-size:12px">{k.get("keyword","")}</span>' for k in keywords[:8]])
        
        html = f"""
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f8fafc; }}
  .container {{ max-width: 600px; margin: 0 auto; background: white; }}
  .header {{ background: linear-gradient(135deg, #4f46e5, #7c3aed); padding: 32px; text-align: center; }}
  .header h1 {{ color: white; margin: 0; font-size: 24px; }}
  .header p {{ color: rgba(255,255,255,0.8); margin: 8px 0 0; font-size: 14px; }}
  .score-box {{ background: #f8fafc; padding: 24px; text-align: center; border-bottom: 1px solid #e2e8f0; }}
  .score {{ font-size: 64px; font-weight: 800; color: {score_color}; line-height: 1; }}
  .score-label {{ color: #64748b; font-size: 14px; margin-top: 4px; }}
  .section {{ padding: 24px; border-bottom: 1px solid #e2e8f0; }}
  .section h2 {{ font-size: 16px; color: #1e293b; margin: 0 0 12px; }}
  .metric {{ display: inline-block; background: #f0f9ff; border: 1px solid #bae6fd; padding: 10px 16px; border-radius: 10px; margin: 4px; text-align: center; }}
  .metric-value {{ font-size: 20px; font-weight: 700; color: #0369a1; }}
  .metric-label {{ font-size: 11px; color: #64748b; margin-top: 2px; }}
  .footer {{ background: #f8fafc; padding: 20px; text-align: center; color: #94a3b8; font-size: 12px; }}
</style></head>
<body>
<div class="container">
  <div class="header">
    <h1>🎯 SEM AI — SEO Report</h1>
    <p>{url}</p>
    <p>Generated on {__import__('datetime').datetime.now().strftime('%d %B %Y')}</p>
  </div>
  
  <div class="score-box">
    <div class="score">{score}</div>
    <div class="score-label">Overall SEO Score / 100</div>
  </div>
  
  <div class="section">
    <h2>🤖 AI Expert Analysis</h2>
    <p style="color:#475569;line-height:1.7;font-size:14px">{summary}</p>
  </div>
  
  <div class="section">
    <h2>📊 SEM Recommendations</h2>
    <div>
      <div class="metric"><div class="metric-value">₹{budget:,}</div><div class="metric-label">Monthly Budget</div></div>
      <div class="metric"><div class="metric-value">{clicks}</div><div class="metric-label">Est. Clicks/mo</div></div>
      <div class="metric"><div class="metric-value">₹{cpc}</div><div class="metric-label">Avg CPC</div></div>
    </div>
  </div>
  
  <div class="section">
    <h2>💪 Strengths</h2>
    <ul style="margin:0;padding-left:16px">{strengths_html}</ul>
  </div>
  
  <div class="section">
    <h2>⚠️ Issues to Fix</h2>
    <ul style="margin:0;padding-left:16px">{weaknesses_html}</ul>
  </div>
  
  <div class="section">
    <h2>🔑 Target Keywords</h2>
    <div>{keywords_html}</div>
  </div>
  
  <div class="footer">
    <p>Generated by SEM AI Platform • Powered by Gemini 2.5 Flash</p>
  </div>
</div>
</body>
</html>"""

        # Send via Resend API
        import httpx as _hx
        resp = _hx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {resend_api_key}", "Content-Type": "application/json"},
            json={
                "from": "SEM AI <onboarding@resend.dev>",
                "to": [email],
                "subject": f"SEO Report: {url} — Score {score}/100",
                "html": html,
            },
            timeout=30
        )
        
        if resp.status_code == 200:
            return {"success": True, "message": f"Report sent to {email}"}
        else:
            return {"success": False, "error": resp.text}
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        return {"success": False, "error": str(e)}

'''

if '/api/send-report' not in content:
    content = content.replace(
        '@app.get("/api/agent/status")',
        email_endpoint + '@app.get("/api/agent/status")'
    )
    print("Email endpoint added!")

with open(main_path, 'w') as f:
    f.write(content)

import py_compile
try:
    py_compile.compile(main_path, doraise=True)
    print("Syntax OK!")
except py_compile.PyCompileError as e:
    print("ERROR:", e)

# 2. Add Send Report button to Dashboard
dash_path = '/Users/sakthivel-1528/Personal/sem-app/backend/frontend/src/components/Dashboard.jsx'
with open(dash_path) as f:
    dcontent = f.read()

# Add email state
old_state = """  const [pageSpeed, setPageSpeed] = useState(null)"""
new_state = """  const [pageSpeed, setPageSpeed] = useState(null)
  const [sendingReport, setSendingReport] = useState(false)
  const [reportSent, setReportSent] = useState(false)
  const [reportEmail, setReportEmail] = useState('')
  const [showEmailInput, setShowEmailInput] = useState(false)"""

dcontent = dcontent.replace(old_state, new_state)

# Add Send Report button after AI Expert Analysis card header
old_header = """              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                <SectionTitle icon={Zap}>AI Expert Analysis</SectionTitle>
                <div style={{ fontSize: '11px', color: 'var(--text3)', padding: '3px 8px', background: 'var(--bg3)', borderRadius: '10px', border: '1px solid var(--border)' }}>
                  🤖 Gemini 2.5 Flash
                </div>
              </div>"""

new_header = """              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                <SectionTitle icon={Zap}>AI Expert Analysis</SectionTitle>
                <div style={{ display: 'flex', gap: '6px', alignItems: 'center' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text3)', padding: '3px 8px', background: 'var(--bg3)', borderRadius: '10px', border: '1px solid var(--border)' }}>
                    🤖 Gemini 2.5 Flash
                  </div>
                  {!reportSent ? (
                    <button onClick={() => setShowEmailInput(!showEmailInput)} style={{ fontSize: '11px', padding: '4px 10px', borderRadius: '7px', background: 'var(--accent)', border: 'none', color: 'white', cursor: 'pointer', fontWeight: 600 }}>
                      📧 Email Report
                    </button>
                  ) : (
                    <span style={{ fontSize: '11px', color: 'var(--green)', fontWeight: 600 }}>✅ Report Sent!</span>
                  )}
                </div>
              </div>
              {showEmailInput && !reportSent && (
                <div style={{ display: 'flex', gap: '6px', marginBottom: '12px' }}>
                  <input value={reportEmail} onChange={e => setReportEmail(e.target.value)} placeholder="Enter email address" style={{ flex: 1, padding: '7px 10px', background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: '7px', color: 'var(--text)', fontSize: '12px', outline: 'none' }} />
                  <button disabled={sendingReport || !reportEmail} onClick={async () => {
                    setSendingReport(true)
                    try {
                      const res = await fetch('https://sem-ai-production.up.railway.app/api/send-report', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ url, email: reportEmail, seo_report: seo })
                      })
                      const data = await res.json()
                      if (data.success) { setReportSent(true); setShowEmailInput(false) }
                      else alert('Failed: ' + data.error)
                    } catch(e) { alert('Error: ' + e.message) }
                    setSendingReport(false)
                  }} style={{ padding: '7px 14px', borderRadius: '7px', background: sendingReport ? 'var(--bg3)' : 'var(--green)', border: 'none', color: 'white', cursor: sendingReport ? 'not-allowed' : 'pointer', fontSize: '12px', fontWeight: 600, flexShrink: 0 }}>
                    {sendingReport ? '⏳ Sending...' : '📤 Send'}
                  </button>
                </div>
              )}"""

dcontent = dcontent.replace(old_header, new_header)

with open(dash_path, 'w') as f:
    f.write(dcontent)

dash_path2 = '/Users/sakthivel-1528/Personal/sem-app/frontend/src/components/Dashboard.jsx'
with open(dash_path2, 'w') as f:
    f.write(dcontent)

print("Email report UI added!")
print("Has reportSent:", "reportSent" in dcontent)
print("Has sendingReport:", "sendingReport" in dcontent)
